// Generated by the protocol buffer compiler. DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: allscenes.proto

// Generated files should ignore deprecation warnings
@file:Suppress("DEPRECATION")
package anime_scenes;

