// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: allscenes.proto
// Protobuf Java Version: 4.27.3

package anime_scenes;

import com.google.protobuf.AbstractMessageLite;

public final class Allscenes {
  private Allscenes() {}
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 27,
      /* patch= */ 3,
      /* suffix= */ "",
      Allscenes.class.getName());
  }
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface SceneOrBuilder extends
      // @@protoc_insertion_point(interface_extends:anime_scenes.Scene)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>double id = 1;</code>
     * @return The id.
     */
    double getId();

    /**
     * <code>string name = 2;</code>
     * @return The name.
     */
    java.lang.String getName();
    /**
     * <code>string name = 2;</code>
     * @return The bytes for name.
     */
    com.google.protobuf.ByteString
        getNameBytes();

    /**
     * <code>string episode = 3;</code>
     * @return The episode.
     */
    java.lang.String getEpisode();
    /**
     * <code>string episode = 3;</code>
     * @return The bytes for episode.
     */
    com.google.protobuf.ByteString
        getEpisodeBytes();

    /**
     * <code>double likes = 4;</code>
     * @return The likes.
     */
    double getLikes();

    /**
     * <code>double startTime = 5;</code>
     * @return The startTime.
     */
    double getStartTime();

    /**
     * <code>string sceneImage = 6;</code>
     * @return The sceneImage.
     */
    java.lang.String getSceneImage();
    /**
     * <code>string sceneImage = 6;</code>
     * @return The bytes for sceneImage.
     */
    com.google.protobuf.ByteString
        getSceneImageBytes();

    /**
     * <code>string description = 7;</code>
     * @return The description.
     */
    java.lang.String getDescription();
    /**
     * <code>string description = 7;</code>
     * @return The bytes for description.
     */
    com.google.protobuf.ByteString
        getDescriptionBytes();
  }
  /**
   * Protobuf type {@code anime_scenes.Scene}
   */
  public static final class Scene extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:anime_scenes.Scene)
      SceneOrBuilder {
  private static final long serialVersionUID = 0L;
    static {
      com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
        com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
        /* major= */ 4,
        /* minor= */ 27,
        /* patch= */ 3,
        /* suffix= */ "",
        Scene.class.getName());
    }
    // Use Scene.newBuilder() to construct.
    private Scene(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
    }
    private Scene() {
      name_ = "";
      episode_ = "";
      sceneImage_ = "";
      description_ = "";
    }

    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return anime_scenes.Allscenes.internal_static_anime_scenes_Scene_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return anime_scenes.Allscenes.internal_static_anime_scenes_Scene_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              anime_scenes.Allscenes.Scene.class, anime_scenes.Allscenes.Scene.Builder.class);
    }

    public static final int ID_FIELD_NUMBER = 1;
    private double id_ = 0D;
    /**
     * <code>double id = 1;</code>
     * @return The id.
     */
    @java.lang.Override
    public double getId() {
      return id_;
    }

    public static final int NAME_FIELD_NUMBER = 2;
    @SuppressWarnings("serial")
    private volatile java.lang.Object name_ = "";
    /**
     * <code>string name = 2;</code>
     * @return The name.
     */
    @java.lang.Override
    public java.lang.String getName() {
      java.lang.Object ref = name_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        name_ = s;
        return s;
      }
    }
    /**
     * <code>string name = 2;</code>
     * @return The bytes for name.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getNameBytes() {
      java.lang.Object ref = name_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        name_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int EPISODE_FIELD_NUMBER = 3;
    @SuppressWarnings("serial")
    private volatile java.lang.Object episode_ = "";
    /**
     * <code>string episode = 3;</code>
     * @return The episode.
     */
    @java.lang.Override
    public java.lang.String getEpisode() {
      java.lang.Object ref = episode_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        episode_ = s;
        return s;
      }
    }
    /**
     * <code>string episode = 3;</code>
     * @return The bytes for episode.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getEpisodeBytes() {
      java.lang.Object ref = episode_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        episode_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int LIKES_FIELD_NUMBER = 4;
    private double likes_ = 0D;
    /**
     * <code>double likes = 4;</code>
     * @return The likes.
     */
    @java.lang.Override
    public double getLikes() {
      return likes_;
    }

    public static final int STARTTIME_FIELD_NUMBER = 5;
    private double startTime_ = 0D;
    /**
     * <code>double startTime = 5;</code>
     * @return The startTime.
     */
    @java.lang.Override
    public double getStartTime() {
      return startTime_;
    }

    public static final int SCENEIMAGE_FIELD_NUMBER = 6;
    @SuppressWarnings("serial")
    private volatile java.lang.Object sceneImage_ = "";
    /**
     * <code>string sceneImage = 6;</code>
     * @return The sceneImage.
     */
    @java.lang.Override
    public java.lang.String getSceneImage() {
      java.lang.Object ref = sceneImage_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        sceneImage_ = s;
        return s;
      }
    }
    /**
     * <code>string sceneImage = 6;</code>
     * @return The bytes for sceneImage.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getSceneImageBytes() {
      java.lang.Object ref = sceneImage_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        sceneImage_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int DESCRIPTION_FIELD_NUMBER = 7;
    @SuppressWarnings("serial")
    private volatile java.lang.Object description_ = "";
    /**
     * <code>string description = 7;</code>
     * @return The description.
     */
    @java.lang.Override
    public java.lang.String getDescription() {
      java.lang.Object ref = description_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        description_ = s;
        return s;
      }
    }
    /**
     * <code>string description = 7;</code>
     * @return The bytes for description.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getDescriptionBytes() {
      java.lang.Object ref = description_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        description_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (java.lang.Double.doubleToRawLongBits(id_) != 0) {
        output.writeDouble(1, id_);
      }
      if (!com.google.protobuf.GeneratedMessage.isStringEmpty(name_)) {
        com.google.protobuf.GeneratedMessage.writeString(output, 2, name_);
      }
      if (!com.google.protobuf.GeneratedMessage.isStringEmpty(episode_)) {
        com.google.protobuf.GeneratedMessage.writeString(output, 3, episode_);
      }
      if (java.lang.Double.doubleToRawLongBits(likes_) != 0) {
        output.writeDouble(4, likes_);
      }
      if (java.lang.Double.doubleToRawLongBits(startTime_) != 0) {
        output.writeDouble(5, startTime_);
      }
      if (!com.google.protobuf.GeneratedMessage.isStringEmpty(sceneImage_)) {
        com.google.protobuf.GeneratedMessage.writeString(output, 6, sceneImage_);
      }
      if (!com.google.protobuf.GeneratedMessage.isStringEmpty(description_)) {
        com.google.protobuf.GeneratedMessage.writeString(output, 7, description_);
      }
      getUnknownFields().writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (java.lang.Double.doubleToRawLongBits(id_) != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeDoubleSize(1, id_);
      }
      if (!com.google.protobuf.GeneratedMessage.isStringEmpty(name_)) {
        size += com.google.protobuf.GeneratedMessage.computeStringSize(2, name_);
      }
      if (!com.google.protobuf.GeneratedMessage.isStringEmpty(episode_)) {
        size += com.google.protobuf.GeneratedMessage.computeStringSize(3, episode_);
      }
      if (java.lang.Double.doubleToRawLongBits(likes_) != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeDoubleSize(4, likes_);
      }
      if (java.lang.Double.doubleToRawLongBits(startTime_) != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeDoubleSize(5, startTime_);
      }
      if (!com.google.protobuf.GeneratedMessage.isStringEmpty(sceneImage_)) {
        size += com.google.protobuf.GeneratedMessage.computeStringSize(6, sceneImage_);
      }
      if (!com.google.protobuf.GeneratedMessage.isStringEmpty(description_)) {
        size += com.google.protobuf.GeneratedMessage.computeStringSize(7, description_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof anime_scenes.Allscenes.Scene)) {
        return super.equals(obj);
      }
      anime_scenes.Allscenes.Scene other = (anime_scenes.Allscenes.Scene) obj;

      if (java.lang.Double.doubleToLongBits(getId())
          != java.lang.Double.doubleToLongBits(
              other.getId())) return false;
      if (!getName()
          .equals(other.getName())) return false;
      if (!getEpisode()
          .equals(other.getEpisode())) return false;
      if (java.lang.Double.doubleToLongBits(getLikes())
          != java.lang.Double.doubleToLongBits(
              other.getLikes())) return false;
      if (java.lang.Double.doubleToLongBits(getStartTime())
          != java.lang.Double.doubleToLongBits(
              other.getStartTime())) return false;
      if (!getSceneImage()
          .equals(other.getSceneImage())) return false;
      if (!getDescription()
          .equals(other.getDescription())) return false;
      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + ID_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          java.lang.Double.doubleToLongBits(getId()));
      hash = (37 * hash) + NAME_FIELD_NUMBER;
      hash = (53 * hash) + getName().hashCode();
      hash = (37 * hash) + EPISODE_FIELD_NUMBER;
      hash = (53 * hash) + getEpisode().hashCode();
      hash = (37 * hash) + LIKES_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          java.lang.Double.doubleToLongBits(getLikes()));
      hash = (37 * hash) + STARTTIME_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          java.lang.Double.doubleToLongBits(getStartTime()));
      hash = (37 * hash) + SCENEIMAGE_FIELD_NUMBER;
      hash = (53 * hash) + getSceneImage().hashCode();
      hash = (37 * hash) + DESCRIPTION_FIELD_NUMBER;
      hash = (53 * hash) + getDescription().hashCode();
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static anime_scenes.Allscenes.Scene parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static anime_scenes.Allscenes.Scene parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static anime_scenes.Allscenes.Scene parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static anime_scenes.Allscenes.Scene parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static anime_scenes.Allscenes.Scene parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static anime_scenes.Allscenes.Scene parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static anime_scenes.Allscenes.Scene parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input);
    }
    public static anime_scenes.Allscenes.Scene parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public static anime_scenes.Allscenes.Scene parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseDelimitedWithIOException(PARSER, input);
    }

    public static anime_scenes.Allscenes.Scene parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static anime_scenes.Allscenes.Scene parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input);
    }
    public static anime_scenes.Allscenes.Scene parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(anime_scenes.Allscenes.Scene prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code anime_scenes.Scene}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:anime_scenes.Scene)
        anime_scenes.Allscenes.SceneOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return anime_scenes.Allscenes.internal_static_anime_scenes_Scene_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return anime_scenes.Allscenes.internal_static_anime_scenes_Scene_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                anime_scenes.Allscenes.Scene.class, anime_scenes.Allscenes.Scene.Builder.class);
      }

      // Construct using anime_scenes.Allscenes.Scene.newBuilder()
      private Builder() {

      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);

      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        bitField0_ = 0;
        id_ = 0D;
        name_ = "";
        episode_ = "";
        likes_ = 0D;
        startTime_ = 0D;
        sceneImage_ = "";
        description_ = "";
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return anime_scenes.Allscenes.internal_static_anime_scenes_Scene_descriptor;
      }

      @java.lang.Override
      public anime_scenes.Allscenes.Scene getDefaultInstanceForType() {
        return anime_scenes.Allscenes.Scene.getDefaultInstance();
      }

      @java.lang.Override
      public anime_scenes.Allscenes.Scene build() {
        anime_scenes.Allscenes.Scene result = buildPartial();
        if (!result.isInitialized()) {
          throw Builder.newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public anime_scenes.Allscenes.Scene buildPartial() {
        anime_scenes.Allscenes.Scene result = new anime_scenes.Allscenes.Scene(this);
        if (bitField0_ != 0) { buildPartial0(result); }
        onBuilt();
        return result;
      }

      private void buildPartial0(anime_scenes.Allscenes.Scene result) {
        int from_bitField0_ = bitField0_;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          result.id_ = id_;
        }
        if (((from_bitField0_ & 0x00000002) != 0)) {
          result.name_ = name_;
        }
        if (((from_bitField0_ & 0x00000004) != 0)) {
          result.episode_ = episode_;
        }
        if (((from_bitField0_ & 0x00000008) != 0)) {
          result.likes_ = likes_;
        }
        if (((from_bitField0_ & 0x00000010) != 0)) {
          result.startTime_ = startTime_;
        }
        if (((from_bitField0_ & 0x00000020) != 0)) {
          result.sceneImage_ = sceneImage_;
        }
        if (((from_bitField0_ & 0x00000040) != 0)) {
          result.description_ = description_;
        }
      }

      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof anime_scenes.Allscenes.Scene) {
          return mergeFrom((anime_scenes.Allscenes.Scene)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(anime_scenes.Allscenes.Scene other) {
        if (other == anime_scenes.Allscenes.Scene.getDefaultInstance()) return this;
        if (other.getId() != 0D) {
          setId(other.getId());
        }
        if (!other.getName().isEmpty()) {
          name_ = other.name_;
          bitField0_ |= 0x00000002;
          onChanged();
        }
        if (!other.getEpisode().isEmpty()) {
          episode_ = other.episode_;
          bitField0_ |= 0x00000004;
          onChanged();
        }
        if (other.getLikes() != 0D) {
          setLikes(other.getLikes());
        }
        if (other.getStartTime() != 0D) {
          setStartTime(other.getStartTime());
        }
        if (!other.getSceneImage().isEmpty()) {
          sceneImage_ = other.sceneImage_;
          bitField0_ |= 0x00000020;
          onChanged();
        }
        if (!other.getDescription().isEmpty()) {
          description_ = other.description_;
          bitField0_ |= 0x00000040;
          onChanged();
        }
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 9: {
                id_ = input.readDouble();
                bitField0_ |= 0x00000001;
                break;
              } // case 9
              case 18: {
                name_ = input.readStringRequireUtf8();
                bitField0_ |= 0x00000002;
                break;
              } // case 18
              case 26: {
                episode_ = input.readStringRequireUtf8();
                bitField0_ |= 0x00000004;
                break;
              } // case 26
              case 33: {
                likes_ = input.readDouble();
                bitField0_ |= 0x00000008;
                break;
              } // case 33
              case 41: {
                startTime_ = input.readDouble();
                bitField0_ |= 0x00000010;
                break;
              } // case 41
              case 50: {
                sceneImage_ = input.readStringRequireUtf8();
                bitField0_ |= 0x00000020;
                break;
              } // case 50
              case 58: {
                description_ = input.readStringRequireUtf8();
                bitField0_ |= 0x00000040;
                break;
              } // case 58
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }
      private int bitField0_;

      private double id_ ;
      /**
       * <code>double id = 1;</code>
       * @return The id.
       */
      @java.lang.Override
      public double getId() {
        return id_;
      }
      /**
       * <code>double id = 1;</code>
       * @param value The id to set.
       * @return This builder for chaining.
       */
      public Builder setId(double value) {

        id_ = value;
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }
      /**
       * <code>double id = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearId() {
        bitField0_ = (bitField0_ & ~0x00000001);
        id_ = 0D;
        onChanged();
        return this;
      }

      private java.lang.Object name_ = "";
      /**
       * <code>string name = 2;</code>
       * @return The name.
       */
      public java.lang.String getName() {
        java.lang.Object ref = name_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          name_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string name = 2;</code>
       * @return The bytes for name.
       */
      public com.google.protobuf.ByteString
          getNameBytes() {
        java.lang.Object ref = name_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          name_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string name = 2;</code>
       * @param value The name to set.
       * @return This builder for chaining.
       */
      public Builder setName(
          java.lang.String value) {
        if (value == null) { throw new NullPointerException(); }
        name_ = value;
        bitField0_ |= 0x00000002;
        onChanged();
        return this;
      }
      /**
       * <code>string name = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearName() {
        name_ = getDefaultInstance().getName();
        bitField0_ = (bitField0_ & ~0x00000002);
        onChanged();
        return this;
      }
      /**
       * <code>string name = 2;</code>
       * @param value The bytes for name to set.
       * @return This builder for chaining.
       */
      public Builder setNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        AbstractMessageLite.checkByteStringIsUtf8(value);
        name_ = value;
        bitField0_ |= 0x00000002;
        onChanged();
        return this;
      }

      private java.lang.Object episode_ = "";
      /**
       * <code>string episode = 3;</code>
       * @return The episode.
       */
      public java.lang.String getEpisode() {
        java.lang.Object ref = episode_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          episode_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string episode = 3;</code>
       * @return The bytes for episode.
       */
      public com.google.protobuf.ByteString
          getEpisodeBytes() {
        java.lang.Object ref = episode_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          episode_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string episode = 3;</code>
       * @param value The episode to set.
       * @return This builder for chaining.
       */
      public Builder setEpisode(
          java.lang.String value) {
        if (value == null) { throw new NullPointerException(); }
        episode_ = value;
        bitField0_ |= 0x00000004;
        onChanged();
        return this;
      }
      /**
       * <code>string episode = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearEpisode() {
        episode_ = getDefaultInstance().getEpisode();
        bitField0_ = (bitField0_ & ~0x00000004);
        onChanged();
        return this;
      }
      /**
       * <code>string episode = 3;</code>
       * @param value The bytes for episode to set.
       * @return This builder for chaining.
       */
      public Builder setEpisodeBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        AbstractMessageLite.checkByteStringIsUtf8(value);
        episode_ = value;
        bitField0_ |= 0x00000004;
        onChanged();
        return this;
      }

      private double likes_ ;
      /**
       * <code>double likes = 4;</code>
       * @return The likes.
       */
      @java.lang.Override
      public double getLikes() {
        return likes_;
      }
      /**
       * <code>double likes = 4;</code>
       * @param value The likes to set.
       * @return This builder for chaining.
       */
      public Builder setLikes(double value) {

        likes_ = value;
        bitField0_ |= 0x00000008;
        onChanged();
        return this;
      }
      /**
       * <code>double likes = 4;</code>
       * @return This builder for chaining.
       */
      public Builder clearLikes() {
        bitField0_ = (bitField0_ & ~0x00000008);
        likes_ = 0D;
        onChanged();
        return this;
      }

      private double startTime_ ;
      /**
       * <code>double startTime = 5;</code>
       * @return The startTime.
       */
      @java.lang.Override
      public double getStartTime() {
        return startTime_;
      }
      /**
       * <code>double startTime = 5;</code>
       * @param value The startTime to set.
       * @return This builder for chaining.
       */
      public Builder setStartTime(double value) {

        startTime_ = value;
        bitField0_ |= 0x00000010;
        onChanged();
        return this;
      }
      /**
       * <code>double startTime = 5;</code>
       * @return This builder for chaining.
       */
      public Builder clearStartTime() {
        bitField0_ = (bitField0_ & ~0x00000010);
        startTime_ = 0D;
        onChanged();
        return this;
      }

      private java.lang.Object sceneImage_ = "";
      /**
       * <code>string sceneImage = 6;</code>
       * @return The sceneImage.
       */
      public java.lang.String getSceneImage() {
        java.lang.Object ref = sceneImage_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          sceneImage_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string sceneImage = 6;</code>
       * @return The bytes for sceneImage.
       */
      public com.google.protobuf.ByteString
          getSceneImageBytes() {
        java.lang.Object ref = sceneImage_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          sceneImage_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string sceneImage = 6;</code>
       * @param value The sceneImage to set.
       * @return This builder for chaining.
       */
      public Builder setSceneImage(
          java.lang.String value) {
        if (value == null) { throw new NullPointerException(); }
        sceneImage_ = value;
        bitField0_ |= 0x00000020;
        onChanged();
        return this;
      }
      /**
       * <code>string sceneImage = 6;</code>
       * @return This builder for chaining.
       */
      public Builder clearSceneImage() {
        sceneImage_ = getDefaultInstance().getSceneImage();
        bitField0_ = (bitField0_ & ~0x00000020);
        onChanged();
        return this;
      }
      /**
       * <code>string sceneImage = 6;</code>
       * @param value The bytes for sceneImage to set.
       * @return This builder for chaining.
       */
      public Builder setSceneImageBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        AbstractMessageLite.checkByteStringIsUtf8(value);
        sceneImage_ = value;
        bitField0_ |= 0x00000020;
        onChanged();
        return this;
      }

      private java.lang.Object description_ = "";
      /**
       * <code>string description = 7;</code>
       * @return The description.
       */
      public java.lang.String getDescription() {
        java.lang.Object ref = description_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          description_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string description = 7;</code>
       * @return The bytes for description.
       */
      public com.google.protobuf.ByteString
          getDescriptionBytes() {
        java.lang.Object ref = description_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          description_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string description = 7;</code>
       * @param value The description to set.
       * @return This builder for chaining.
       */
      public Builder setDescription(
          java.lang.String value) {
        if (value == null) { throw new NullPointerException(); }
        description_ = value;
        bitField0_ |= 0x00000040;
        onChanged();
        return this;
      }
      /**
       * <code>string description = 7;</code>
       * @return This builder for chaining.
       */
      public Builder clearDescription() {
        description_ = getDefaultInstance().getDescription();
        bitField0_ = (bitField0_ & ~0x00000040);
        onChanged();
        return this;
      }
      /**
       * <code>string description = 7;</code>
       * @param value The bytes for description to set.
       * @return This builder for chaining.
       */
      public Builder setDescriptionBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        AbstractMessageLite.checkByteStringIsUtf8(value);
        description_ = value;
        bitField0_ |= 0x00000040;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:anime_scenes.Scene)
    }

    // @@protoc_insertion_point(class_scope:anime_scenes.Scene)
    private static final anime_scenes.Allscenes.Scene DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new anime_scenes.Allscenes.Scene();
    }

    public static anime_scenes.Allscenes.Scene getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Scene>
        PARSER = new com.google.protobuf.AbstractParser<Scene>() {
      @java.lang.Override
      public Scene parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<Scene> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Scene> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public anime_scenes.Allscenes.Scene getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface AllRankedScenesOrBuilder extends
      // @@protoc_insertion_point(interface_extends:anime_scenes.AllRankedScenes)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>repeated .anime_scenes.Scene scenes = 1;</code>
     */
    java.util.List<anime_scenes.Allscenes.Scene> 
        getScenesList();
    /**
     * <code>repeated .anime_scenes.Scene scenes = 1;</code>
     */
    anime_scenes.Allscenes.Scene getScenes(int index);
    /**
     * <code>repeated .anime_scenes.Scene scenes = 1;</code>
     */
    int getScenesCount();
    /**
     * <code>repeated .anime_scenes.Scene scenes = 1;</code>
     */
    java.util.List<? extends anime_scenes.Allscenes.SceneOrBuilder> 
        getScenesOrBuilderList();
    /**
     * <code>repeated .anime_scenes.Scene scenes = 1;</code>
     */
    anime_scenes.Allscenes.SceneOrBuilder getScenesOrBuilder(
        int index);
  }
  /**
   * Protobuf type {@code anime_scenes.AllRankedScenes}
   */
  public static final class AllRankedScenes extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:anime_scenes.AllRankedScenes)
      AllRankedScenesOrBuilder {
  private static final long serialVersionUID = 0L;
    static {
      com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
        com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
        /* major= */ 4,
        /* minor= */ 27,
        /* patch= */ 3,
        /* suffix= */ "",
        AllRankedScenes.class.getName());
    }
    // Use AllRankedScenes.newBuilder() to construct.
    private AllRankedScenes(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
    }
    private AllRankedScenes() {
      scenes_ = java.util.Collections.emptyList();
    }

    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return anime_scenes.Allscenes.internal_static_anime_scenes_AllRankedScenes_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return anime_scenes.Allscenes.internal_static_anime_scenes_AllRankedScenes_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              anime_scenes.Allscenes.AllRankedScenes.class, anime_scenes.Allscenes.AllRankedScenes.Builder.class);
    }

    public static final int SCENES_FIELD_NUMBER = 1;
    @SuppressWarnings("serial")
    private java.util.List<anime_scenes.Allscenes.Scene> scenes_;
    /**
     * <code>repeated .anime_scenes.Scene scenes = 1;</code>
     */
    @java.lang.Override
    public java.util.List<anime_scenes.Allscenes.Scene> getScenesList() {
      return scenes_;
    }
    /**
     * <code>repeated .anime_scenes.Scene scenes = 1;</code>
     */
    @java.lang.Override
    public java.util.List<? extends anime_scenes.Allscenes.SceneOrBuilder> 
        getScenesOrBuilderList() {
      return scenes_;
    }
    /**
     * <code>repeated .anime_scenes.Scene scenes = 1;</code>
     */
    @java.lang.Override
    public int getScenesCount() {
      return scenes_.size();
    }
    /**
     * <code>repeated .anime_scenes.Scene scenes = 1;</code>
     */
    @java.lang.Override
    public anime_scenes.Allscenes.Scene getScenes(int index) {
      return scenes_.get(index);
    }
    /**
     * <code>repeated .anime_scenes.Scene scenes = 1;</code>
     */
    @java.lang.Override
    public anime_scenes.Allscenes.SceneOrBuilder getScenesOrBuilder(
        int index) {
      return scenes_.get(index);
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      for (int i = 0; i < scenes_.size(); i++) {
        output.writeMessage(1, scenes_.get(i));
      }
      getUnknownFields().writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      for (int i = 0; i < scenes_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, scenes_.get(i));
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof anime_scenes.Allscenes.AllRankedScenes)) {
        return super.equals(obj);
      }
      anime_scenes.Allscenes.AllRankedScenes other = (anime_scenes.Allscenes.AllRankedScenes) obj;

      if (!getScenesList()
          .equals(other.getScenesList())) return false;
      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (getScenesCount() > 0) {
        hash = (37 * hash) + SCENES_FIELD_NUMBER;
        hash = (53 * hash) + getScenesList().hashCode();
      }
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static anime_scenes.Allscenes.AllRankedScenes parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static anime_scenes.Allscenes.AllRankedScenes parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static anime_scenes.Allscenes.AllRankedScenes parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static anime_scenes.Allscenes.AllRankedScenes parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static anime_scenes.Allscenes.AllRankedScenes parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static anime_scenes.Allscenes.AllRankedScenes parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static anime_scenes.Allscenes.AllRankedScenes parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input);
    }
    public static anime_scenes.Allscenes.AllRankedScenes parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public static anime_scenes.Allscenes.AllRankedScenes parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseDelimitedWithIOException(PARSER, input);
    }

    public static anime_scenes.Allscenes.AllRankedScenes parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static anime_scenes.Allscenes.AllRankedScenes parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input);
    }
    public static anime_scenes.Allscenes.AllRankedScenes parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(anime_scenes.Allscenes.AllRankedScenes prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code anime_scenes.AllRankedScenes}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:anime_scenes.AllRankedScenes)
        anime_scenes.Allscenes.AllRankedScenesOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return anime_scenes.Allscenes.internal_static_anime_scenes_AllRankedScenes_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return anime_scenes.Allscenes.internal_static_anime_scenes_AllRankedScenes_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                anime_scenes.Allscenes.AllRankedScenes.class, anime_scenes.Allscenes.AllRankedScenes.Builder.class);
      }

      // Construct using anime_scenes.Allscenes.AllRankedScenes.newBuilder()
      private Builder() {

      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);

      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        bitField0_ = 0;
        if (scenesBuilder_ == null) {
          scenes_ = java.util.Collections.emptyList();
        } else {
          scenes_ = null;
          scenesBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000001);
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return anime_scenes.Allscenes.internal_static_anime_scenes_AllRankedScenes_descriptor;
      }

      @java.lang.Override
      public anime_scenes.Allscenes.AllRankedScenes getDefaultInstanceForType() {
        return anime_scenes.Allscenes.AllRankedScenes.getDefaultInstance();
      }

      @java.lang.Override
      public anime_scenes.Allscenes.AllRankedScenes build() {
        anime_scenes.Allscenes.AllRankedScenes result = buildPartial();
        if (!result.isInitialized()) {
          throw Builder.newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public anime_scenes.Allscenes.AllRankedScenes buildPartial() {
        anime_scenes.Allscenes.AllRankedScenes result = new anime_scenes.Allscenes.AllRankedScenes(this);
        buildPartialRepeatedFields(result);
        if (bitField0_ != 0) { buildPartial0(result); }
        onBuilt();
        return result;
      }

      private void buildPartialRepeatedFields(anime_scenes.Allscenes.AllRankedScenes result) {
        if (scenesBuilder_ == null) {
          if (((bitField0_ & 0x00000001) != 0)) {
            scenes_ = java.util.Collections.unmodifiableList(scenes_);
            bitField0_ = (bitField0_ & ~0x00000001);
          }
          result.scenes_ = scenes_;
        } else {
          result.scenes_ = scenesBuilder_.build();
        }
      }

      private void buildPartial0(anime_scenes.Allscenes.AllRankedScenes result) {
        int from_bitField0_ = bitField0_;
      }

      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof anime_scenes.Allscenes.AllRankedScenes) {
          return mergeFrom((anime_scenes.Allscenes.AllRankedScenes)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(anime_scenes.Allscenes.AllRankedScenes other) {
        if (other == anime_scenes.Allscenes.AllRankedScenes.getDefaultInstance()) return this;
        if (scenesBuilder_ == null) {
          if (!other.scenes_.isEmpty()) {
            if (scenes_.isEmpty()) {
              scenes_ = other.scenes_;
              bitField0_ = (bitField0_ & ~0x00000001);
            } else {
              ensureScenesIsMutable();
              scenes_.addAll(other.scenes_);
            }
            onChanged();
          }
        } else {
          if (!other.scenes_.isEmpty()) {
            if (scenesBuilder_.isEmpty()) {
              scenesBuilder_.dispose();
              scenesBuilder_ = null;
              scenes_ = other.scenes_;
              bitField0_ = (bitField0_ & ~0x00000001);
              scenesBuilder_ = 
                com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders ?
                   getScenesFieldBuilder() : null;
            } else {
              scenesBuilder_.addAllMessages(other.scenes_);
            }
          }
        }
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 10: {
                anime_scenes.Allscenes.Scene m =
                    input.readMessage(
                        anime_scenes.Allscenes.Scene.parser(),
                        extensionRegistry);
                if (scenesBuilder_ == null) {
                  ensureScenesIsMutable();
                  scenes_.add(m);
                } else {
                  scenesBuilder_.addMessage(m);
                }
                break;
              } // case 10
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }
      private int bitField0_;

      private java.util.List<anime_scenes.Allscenes.Scene> scenes_ =
        java.util.Collections.emptyList();
      private void ensureScenesIsMutable() {
        if (!((bitField0_ & 0x00000001) != 0)) {
          scenes_ = new java.util.ArrayList<anime_scenes.Allscenes.Scene>(scenes_);
          bitField0_ |= 0x00000001;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilder<
          anime_scenes.Allscenes.Scene, anime_scenes.Allscenes.Scene.Builder, anime_scenes.Allscenes.SceneOrBuilder> scenesBuilder_;

      /**
       * <code>repeated .anime_scenes.Scene scenes = 1;</code>
       */
      public java.util.List<anime_scenes.Allscenes.Scene> getScenesList() {
        if (scenesBuilder_ == null) {
          return java.util.Collections.unmodifiableList(scenes_);
        } else {
          return scenesBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .anime_scenes.Scene scenes = 1;</code>
       */
      public int getScenesCount() {
        if (scenesBuilder_ == null) {
          return scenes_.size();
        } else {
          return scenesBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .anime_scenes.Scene scenes = 1;</code>
       */
      public anime_scenes.Allscenes.Scene getScenes(int index) {
        if (scenesBuilder_ == null) {
          return scenes_.get(index);
        } else {
          return scenesBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .anime_scenes.Scene scenes = 1;</code>
       */
      public Builder setScenes(
          int index, anime_scenes.Allscenes.Scene value) {
        if (scenesBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureScenesIsMutable();
          scenes_.set(index, value);
          onChanged();
        } else {
          scenesBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .anime_scenes.Scene scenes = 1;</code>
       */
      public Builder setScenes(
          int index, anime_scenes.Allscenes.Scene.Builder builderForValue) {
        if (scenesBuilder_ == null) {
          ensureScenesIsMutable();
          scenes_.set(index, builderForValue.build());
          onChanged();
        } else {
          scenesBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .anime_scenes.Scene scenes = 1;</code>
       */
      public Builder addScenes(anime_scenes.Allscenes.Scene value) {
        if (scenesBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureScenesIsMutable();
          scenes_.add(value);
          onChanged();
        } else {
          scenesBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .anime_scenes.Scene scenes = 1;</code>
       */
      public Builder addScenes(
          int index, anime_scenes.Allscenes.Scene value) {
        if (scenesBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureScenesIsMutable();
          scenes_.add(index, value);
          onChanged();
        } else {
          scenesBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .anime_scenes.Scene scenes = 1;</code>
       */
      public Builder addScenes(
          anime_scenes.Allscenes.Scene.Builder builderForValue) {
        if (scenesBuilder_ == null) {
          ensureScenesIsMutable();
          scenes_.add(builderForValue.build());
          onChanged();
        } else {
          scenesBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .anime_scenes.Scene scenes = 1;</code>
       */
      public Builder addScenes(
          int index, anime_scenes.Allscenes.Scene.Builder builderForValue) {
        if (scenesBuilder_ == null) {
          ensureScenesIsMutable();
          scenes_.add(index, builderForValue.build());
          onChanged();
        } else {
          scenesBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .anime_scenes.Scene scenes = 1;</code>
       */
      public Builder addAllScenes(
          java.lang.Iterable<? extends anime_scenes.Allscenes.Scene> values) {
        if (scenesBuilder_ == null) {
          ensureScenesIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
              values, scenes_);
          onChanged();
        } else {
          scenesBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .anime_scenes.Scene scenes = 1;</code>
       */
      public Builder clearScenes() {
        if (scenesBuilder_ == null) {
          scenes_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
          onChanged();
        } else {
          scenesBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .anime_scenes.Scene scenes = 1;</code>
       */
      public Builder removeScenes(int index) {
        if (scenesBuilder_ == null) {
          ensureScenesIsMutable();
          scenes_.remove(index);
          onChanged();
        } else {
          scenesBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .anime_scenes.Scene scenes = 1;</code>
       */
      public anime_scenes.Allscenes.Scene.Builder getScenesBuilder(
          int index) {
        return getScenesFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .anime_scenes.Scene scenes = 1;</code>
       */
      public anime_scenes.Allscenes.SceneOrBuilder getScenesOrBuilder(
          int index) {
        if (scenesBuilder_ == null) {
          return scenes_.get(index);  } else {
          return scenesBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .anime_scenes.Scene scenes = 1;</code>
       */
      public java.util.List<? extends anime_scenes.Allscenes.SceneOrBuilder> 
           getScenesOrBuilderList() {
        if (scenesBuilder_ != null) {
          return scenesBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(scenes_);
        }
      }
      /**
       * <code>repeated .anime_scenes.Scene scenes = 1;</code>
       */
      public anime_scenes.Allscenes.Scene.Builder addScenesBuilder() {
        return getScenesFieldBuilder().addBuilder(
            anime_scenes.Allscenes.Scene.getDefaultInstance());
      }
      /**
       * <code>repeated .anime_scenes.Scene scenes = 1;</code>
       */
      public anime_scenes.Allscenes.Scene.Builder addScenesBuilder(
          int index) {
        return getScenesFieldBuilder().addBuilder(
            index, anime_scenes.Allscenes.Scene.getDefaultInstance());
      }
      /**
       * <code>repeated .anime_scenes.Scene scenes = 1;</code>
       */
      public java.util.List<anime_scenes.Allscenes.Scene.Builder> 
           getScenesBuilderList() {
        return getScenesFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilder<
          anime_scenes.Allscenes.Scene, anime_scenes.Allscenes.Scene.Builder, anime_scenes.Allscenes.SceneOrBuilder> 
          getScenesFieldBuilder() {
        if (scenesBuilder_ == null) {
          scenesBuilder_ = new com.google.protobuf.RepeatedFieldBuilder<
              anime_scenes.Allscenes.Scene, anime_scenes.Allscenes.Scene.Builder, anime_scenes.Allscenes.SceneOrBuilder>(
                  scenes_,
                  ((bitField0_ & 0x00000001) != 0),
                  getParentForChildren(),
                  isClean());
          scenes_ = null;
        }
        return scenesBuilder_;
      }

      // @@protoc_insertion_point(builder_scope:anime_scenes.AllRankedScenes)
    }

    // @@protoc_insertion_point(class_scope:anime_scenes.AllRankedScenes)
    private static final anime_scenes.Allscenes.AllRankedScenes DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new anime_scenes.Allscenes.AllRankedScenes();
    }

    public static anime_scenes.Allscenes.AllRankedScenes getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<AllRankedScenes>
        PARSER = new com.google.protobuf.AbstractParser<AllRankedScenes>() {
      @java.lang.Override
      public AllRankedScenes parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<AllRankedScenes> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<AllRankedScenes> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public anime_scenes.Allscenes.AllRankedScenes getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_anime_scenes_Scene_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_anime_scenes_Scene_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_anime_scenes_AllRankedScenes_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_anime_scenes_AllRankedScenes_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\017allscenes.proto\022\014anime_scenes\"}\n\005Scene" +
      "\022\n\n\002id\030\001 \001(\001\022\014\n\004name\030\002 \001(\t\022\017\n\007episode\030\003 " +
      "\001(\t\022\r\n\005likes\030\004 \001(\001\022\021\n\tstartTime\030\005 \001(\001\022\022\n" +
      "\nsceneImage\030\006 \001(\t\022\023\n\013description\030\007 \001(\t\"6" +
      "\n\017AllRankedScenes\022#\n\006scenes\030\001 \003(\0132\023.anim" +
      "e_scenes.Sceneb\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_anime_scenes_Scene_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_anime_scenes_Scene_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_anime_scenes_Scene_descriptor,
        new java.lang.String[] { "Id", "Name", "Episode", "Likes", "StartTime", "SceneImage", "Description", });
    internal_static_anime_scenes_AllRankedScenes_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_anime_scenes_AllRankedScenes_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_anime_scenes_AllRankedScenes_descriptor,
        new java.lang.String[] { "Scenes", });
    descriptor.resolveAllFeaturesImmutable();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
